[workspace]
resolver = "3"
members = ["cat-sim", "cat-protocol"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
license = "MIT"
repository = "https://git.heerlab.com/beasty/cat_idler"

[workspace.dependencies]
cat-protocol = { path = "cat-protocol" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
