#!/usr/bin/env python3
"""Translate the executable Rust catalog export into Unity-independent C# data.

Run cargo run --manifest-path tools/catalog-export/Cargo.toml --quiet >
tools/catalog-export/catalog.json, then python3 tools/catalog-export/generate.py.
Runtime descriptors and stable research payloads come from compiled maintained code.
Finite recipe quantities below transcribe the small Rust physical-recipe functions;
food/plant arms are parsed from those functions and fail closed on missing entries.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
data = json.loads((Path(__file__).parent / 'catalog.json').read_text())
source = (ROOT / 'tools/save-import/legacy/cat-sim/src/station_recipes.rs').read_text()
tick = (ROOT / 'tools/save-import/legacy/cat-sim/src/world_tick.rs').read_text()
constants = dict(re.findall(r'pub const (\w+): &str = "([^"]+)";', source))
food = {}
for name, inp, amount, out, quantity in re.findall(r'recipes::(\w+) => \(\s*ResourceKind::(\w+),\s*([\d.]+),\s*ResourceKind::(\w+),\s*([\d.]+),', tick):
    food[constants[name]] = (float(amount), float(quantity))
base = {
    'materials_to_refined': (5,1,600),'logs_to_planks': (5,1,600),'stone_to_blocks': (5,1,600),
    'logs_to_lumber': (5,2,600),'grain_to_flour': (4,2,600),'flour_to_food': (2,4,600),
    'fibre_to_thread': (5,5,600),'fibre_to_cloth': (5,1,600),'hide_to_leather': (5,1,600),
    'ore_to_metal': (5,1,600),'smithy_weapon': (2,1,900),'smithy_tool': (2,1,900),
    'smithy_armor': (2,1,900),'planks_and_blocks_to_tools': (2,1,600),
}
tiers = {'preparation':0,'staples':1,'quality':2,'specialty':3,'masterwork':4}
industrial = {'textile_work','leatherworking','carpentry','stonecraft','metallurgy','toolmaking','weaponcraft','armorcraft'}
q = lambda x: json.dumps(x, ensure_ascii=False)
number = lambda x: repr(float(x))
stacks = lambda names, amounts: 'new List<Stack>{'+','.join('new Stack('+q(n)+','+number(a)+')' for n,a in zip(names,amounts))+'}'
lines = ['// Generated by tools/catalog-export/generate.py; do not edit.', 'using System.Collections.Generic;', 'namespace IdleCatForest.Simulation { public static partial class Catalog {', 'private static List<Recipe> CreateRecipes()=>new List<Recipe>{']
for r in data['recipes']:
    rid=r['id']; amount=output=None; seconds=600
    family, _, suffix = rid.rpartition('_'); tier = tiers.get(suffix) if family in industrial else None
    item=r['item']
    if rid in base: amount,output,seconds=base[rid]
    elif rid in food: amount,output=food[rid]
    elif item:
        inp=r['inputs'][0]
        amount=([6,5,5,4,3][tier] if tier is not None else 3) if inp=='metal' else 1 if inp=='gem' else 2 if inp in ('bone','clay','hide') else 3
        output=1
    elif tier is not None: amount,output=[4,5,6,7,8][tier],[3,4,5,6,8][tier]
    else: raise ValueError('Unmapped physical amounts: '+rid)
    outputs=r['outputs']
    if outputs and outputs[0] in ('tools','weapons','armor'):
        item={'kind':{'tools':'tool','weapons':'weapon','armor':'armor'}[outputs[0]],'material':'wood' if r['building']=='woodworking' else 'metal','quality':1}; outputs=[]
    station=r['building'];labor='mill' if station=='mill' else 'craft' if station=='woodworking' else 'textile' if station in ('clothier','tannery') else 'metalwork' if station in ('smithy','smelter') else 'process'
    fields={'Id':q(rid),'Name':q(rid.replace('_',' ').title()),'Building':q(station),'Labor':q(labor),'Founding':str(r['founding']).lower(),'Seconds':number(seconds),'Inputs':stacks(r['inputs'],[amount]*len(r['inputs'])),'Outputs':stacks(outputs,[output]*len(outputs))}
    if item: fields.update(ItemKind=q(item['kind']),Material=q(item['material']),Quality=str(item['quality']))
    lines.append('new Recipe{'+','.join(k+'='+v for k,v in fields.items())+'},')
lines += ['};','private static List<Study> CreateResearch()=>new List<Study>{']
for n in data['research']:
    payloads=[]
    for p in n['payloads']:
        pid=next((p[k] for k in ('building_id','recipe_id','resource_id','job_id','effect_id','capability_id') if k in p),'')
        fields={'Kind':q(p['kind']),'Id':q(pid),'Attribute':q(p.get('attribute','')),'Operation':q(p.get('operation','')),'Value':number(p.get('value',0))}
        payloads.append('new ResearchPayload{'+','.join(k+'='+v for k,v in fields.items())+'}')
    fields={'Id':q(n['id']),'Name':q(n['name']),'Description':q(n['description']),'Category':q(n['category']),'Cost':number(n['cost']),'Era':str(n['era']),'X':str(n['layout']['x']),'Z':str(n['layout']['y']),'LeaderPriority':str(n['leaderPriority']),'Prerequisites':'new List<string>{'+','.join(map(q,n['prerequisites']))+'}','Payloads':'new List<ResearchPayload>{'+','.join(payloads)+'}'}
    lines.append('new Study{'+','.join(k+'='+v for k,v in fields.items())+'},')
lines += ['};','}}']
assert len(data['recipes'])==108 and len(data['research'])==487
out=ROOT / 'unity/Assets/Forest/Simulation/Catalog.Generated.cs'
out.write_text('\n'.join(lines)+'\n')
print('Exported 108 physical recipes and 487 exact research nodes to',out)
